language: php

php:
  - 5.3
  - 5.4

env:
  - MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD_EXT_VERSION=master

before_script:
  - ./test/travis_midgard2.sh
  - wget http://getcomposer.org/composer.phar 
  - php composer.phar install --dev
  - sudo cp schemas/* /usr/share/midgard2/schema

script: phpunit --debug

notifications:
    irc: "irc.freenode.org#midgard"
